
import time
import turtle

def draw_body_part(body_part):
    turtle.penup()
    turtle.goto(50, 100)
    turtle.pendown()
    for _ in range(2):
        turtle.forward(30)
        turtle.backward(30)
        turtle.left(100)
    turtle.penup()
    turtle.setheading(0)
    turtle.goto(body_part[0], body_part[1])
    turtle.dot(10, "white")
    turtle.pendown()

def forward_roll_animation():
    turtle.left(90)
    time.sleep(0.2)
    time.sleep(0.2)
    turtle.penup()
    turtle.goto(0, 130)
    turtle.pendown()
    turtle.dot(10, "white")
    time.sleep(0.2)
    time.sleep(0.2)
    turtle.setheading(0)
    time.sleep(0.2)
    turtle.forward(30)
    time.sleep(0.2)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.penup()
    turtle.goto(50, 150)
    turtle.pendown()
    time.sleep(0.2)
    turtle.backward(30)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.left(100)
    time.sleep(0.2)
    turtle.backward(30)
    time.sleep(0.2)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.right(100)
    turtle.penup()
    turtle.goto(-50, 120)
    turtle.pendown()
    time.sleep(0.2)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(0, 130)
    time.sleep(0.2)
    turtle.goto(50, 130)
    turtle.dot(10, "white")
    turtle.goto(50, 140)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(50, 150)
    time.sleep(0.2)
    turtle.backward(30)
    time.sleep(0.2)
    turtle.dot(10, "white")
    time.sleep(0.1)
    turtle.goto(50, 160)
    time.sleep(0.2)
    time.sleep(0.2)
    turtle.goto(50, 140)
    time.sleep(0.2)
    time.sleep(0.2)
    turtle.goto(50, 150)
    time.sleep(0.2)
    turtle.goto(50, 160)
    time.sleep(0.2)
    turtle.goto(50, 120)
    time.sleep(0.2)
    time.sleep(0.2)
    turtle.goto(25, 180)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(0, 160)
    turtle.dot(10, "white")
    time.sleep(0.2)
    time.sleep(0.2)
    turtle.goto(25, 170)
    time.sleep(0.2)
    turtle.goto(50, 160)
    turtle.dot(10, "white")
    turtle.goto(25, 160)
    time.sleep(0.2)
    turtle.penup()
    turtle.goto(-50, 0)
    turtle.pendown()
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(50, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(100, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(150, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(200, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(250, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(300, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(350, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(400, 0)
    turtle.dot(10, "white")
    time.sleep(0.2)
    turtle.goto(400, 10)
    time.sleep(0.2)
    turtle.goto(400, -10)
    time.sleep(0.2)
    turtle.goto(400, 0)
    turtle.hideturtle()

def main():
    turtle.bgcolor("black")
    turtle.speed(0)
    head_position = (50, 50)
    upper_arm_position = (50, 20)
    forearm_position = (50, 0)
    draw_body_part(head_position)
    draw_body_part(upper_arm_position)
    draw_body_part(forearm_position)
    
    forward_roll_animation()
    turtle.done()

main()
